[package]
name = "pwd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true
opt-level = 'z'
overflow-checks = false
